In [10]:
import numpy as np
a=[1,2,3,4,5,6]
type(a)
b=np.array(a)
type(b)
c=[20,30,40,50]c)




<>:7: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
<>:7: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
/tmp/ipython-input-10-1797955275.py:7: SyntaxWarning: 'tuple' object is not callable; perhaps you missed a comma?
  np.zeros((2,5)(3,6)(5,9)(6,0))


TypeError: 'tuple' object is not callable

In [11]:
c=np.zeros((2,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
a=np.ones((3,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
a=np.random.rand(2,8)
print(a)

[[0.37135181 0.14502902 0.30591714 0.32328383 0.84633486 0.30532461
  0.66834684 0.47992464]
 [0.18830199 0.55833007 0.83324972 0.48010663 0.31353828 0.43482486
  0.23696257 0.30732515]]


In [23]:
a=np.random.randint(1,20,size=[3,5])
print(a)

[[16 10 15 10 17]
 [ 8  4  4 11 14]
 [ 8 16  7 13 10]]


In [47]:
a=np.random.choice((2,4,5,6))
print(a)

2


In [48]:
a=np.full((9,6),8)
print(a)

[[8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]
 [8 8 8 8 8 8]]


In [50]:
a=np.eye(4,k=-2)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [53]:
a=np.arange(1,3)
print(a)

[1 2]


In [62]:
a=np.arange(1,5,2)
print(a)

[1 3]


In [65]:
a=np.linspace(10,40,5)
print(a)

[10.  17.5 25.  32.5 40. ]


In [67]:
a=[1,2,3,4,5]
b=np.array(a)
b.ndim

1

In [69]:
a=[1,2,3,4,5]
b=[5,6,7,8,0]
c=np.array([a,b])
c.ndim

2

In [74]:
a=[1,2,3,4,5]
b=[5,6,7,8,3]
c=np.array([a,b])
c.shape

(2, 5)

In [75]:
a=[1,2,3,4,5]
b=[5,6,7,8,3]
c=np.array([a,b])
c.size

10