In [8]:
import numpy as np
a=np.array([5,6,9,2])
print(a)

[5 6 9 2]


In [13]:
import numpy as np
a=np.array([5,6,9,2])
print(a)
np.reshape(a,(2,2))

[5 6 9 2]


array([[5, 6],
       [9, 2]])

In [26]:
import numpy as np
a=np.array([5,6,9,2])
np.reshape(a,(2,2))


array([[5, 6],
       [9, 2]])

In [17]:
x=np.arange(1,20)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [21]:
x=np.arange(1,20)
x
x.size

19

In [31]:
x=np.arange(1,16)
x
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [51]:
x = np.arange(1,15)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [53]:
y = x.reshape(2,7)
print(y)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [59]:
z=np.transpose(y)
print(z)
z.transpose()

[[ 1  8]
 [ 2  9]
 [ 3 10]
 [ 4 11]
 [ 5 12]
 [ 6 13]
 [ 7 14]]


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [60]:
z.transpose()

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [62]:
import numpy as np
a=np.arange(1,11)
print(a)
a[1:10]

[ 1  2  3  4  5  6  7  8  9 10]


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
import numpy as np
x=np.arange(1,13).reshape(4,3)
print(x)
x

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
