# broadcasting in numpy arrays



In [4]:
import numpy as np
a = np.arange(1,10,2)
b = np.array([[2],[4]])
print(a)
print(b)
z=a+b
print(z)

[1 3 5 7 9]
[[2]
 [4]]
[[ 3  5  7  9 11]
 [ 5  7  9 11 13]]


In [7]:
import numpy as np
a=np.arange(10,22,2)
a+2

array([12, 14, 16, 18, 20, 22])

In [8]:
a-b

array([[ 8, 10, 12, 14, 16, 18],
       [ 6,  8, 10, 12, 14, 16]])

In [9]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [40, 48, 56, 64, 72, 80]])

In [12]:
a=np.ones((4,4))
b=np.array([2])
print(a)
print(b)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[2]


In [13]:
a+b

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [14]:
a-b

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.]])

# arithmetic operations on numpy array

In [15]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
a+5


array([[6., 5., 5.],
       [5., 6., 5.],
       [5., 5., 6.]])

In [19]:
a-2

array([[-1., -2., -2.],
       [-2., -1., -2.],
       [-2., -2., -1.]])

In [20]:
a*5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [21]:
a/5

array([[0.2, 0. , 0. ],
       [0. , 0.2, 0. ],
       [0. , 0. , 0.2]])

In [22]:
np.sin(a)

array([[0.84147098, 0.        , 0.        ],
       [0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.84147098]])

In [23]:
np.cos(a)

array([[0.54030231, 1.        , 1.        ],
       [1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 0.54030231]])

In [24]:
np.sqrt(a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# aggregate function

mean,median,and standard deviation


In [30]:
a=np.arange(1,10,2)
print(a)
np.mean(a)



[1 3 5 7 9]


np.float64(5.0)

In [31]:
np.median(a)

np.float64(5.0)

In [32]:
np.std(a)

np.float64(2.8284271247461903)

# mini maxvalues

In [33]:
a = np.array([[2,3],[3,2]])
print(a)

[[2 3]
 [3 2]]


In [34]:
print(np.min(a,axis=0))

[2 2]


In [36]:
print(np.max(a,axis=1))

[3 3]


In [37]:
print(np.max(a,axis=0))


[3 3]


# sorting

In [38]:
a = np.array([3,2,10,7,5,3])
b=np.sort(a,kind='mergesort')
print(b)

[ 2  3  3  5  7 10]


# matrix multiplication

In [50]:
import numpy as np
A= np.arange(1,10).reshape(3,3)
B = np.arange(1,10).reshape(3,3)
print(A)
print(B)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
np.dot(A,B)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [52]:
A.dot(B)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])