In [ ]:
import numpy as np
a = np.arange(1,5)
print(a)

[1 2 3 4]


In [ ]:
a[1:5]

array([2, 3, 4])

In [ ]:
x=np.arange(1,13).reshape(4,3)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
x[3,2]

np.int64(12)

In [ ]:
x[3][2]

np.int64(12)

In [ ]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

# stacking and concatenating numpy arrays


# stacking

In [ ]:
a=np.arange(1,5)
b=np.arange(5,9)
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [ ]:
x=np.vstack((a,b))
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
x=np.hstack((a,b))
print(x)

[1 2 3 4 5 6 7 8]


# concatenation

In [52]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
print(a)
print(b)
np.concatenate((a,b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [55]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

# **broadcasting in numpys**

In [57]:
a=np.arange(10,50,2)
b=np.array([[2],[2]])
print(a)
print(b)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[[2]
 [2]]
